IF 3 > 2
  PRINT 'Weekend';

IF DATENAME(WEEKDAY,GETDATE()) IN ('Saturday','Sunday')
	SELECT 'WEEKEND'
ELSE 
	SELECT 'WEEKDAY'

PRINT DATENAME(WEEKDAY,GETDATE())

SELECT COUNT(@@ROWCOUNT)
FROM Production.Product

DECLARE @COUNTER INT = 1
WHILE @COUNTER <= 1000000
BEGIN
	PRINT @COUNTER
	SET @COUNTER += 1
END;